//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMarketAppEntities : DbContext
    {
        public DBMarketAppEntities()
            : base("name=DBMarketAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblAppCurrency> TblAppCurrency { get; set; }
        public virtual DbSet<TblCashSaleDetail> TblCashSaleDetail { get; set; }
        public virtual DbSet<TblCompany> TblCompany { get; set; }
        public virtual DbSet<TblCompanyHasFactory> TblCompanyHasFactory { get; set; }
        public virtual DbSet<TblCompanyHasMarket> TblCompanyHasMarket { get; set; }
        public virtual DbSet<TblCompanyHasWarehouse> TblCompanyHasWarehouse { get; set; }
        public virtual DbSet<TblCompanyOwerHasCompany> TblCompanyOwerHasCompany { get; set; }
        public virtual DbSet<TblCompanyOwner> TblCompanyOwner { get; set; }
        public virtual DbSet<TblCompanyType> TblCompanyType { get; set; }
        public virtual DbSet<TblCountry> TblCountry { get; set; }
        public virtual DbSet<TblCreditCardSaleDetail> TblCreditCardSaleDetail { get; set; }
        public virtual DbSet<TblCurrency> TblCurrency { get; set; }
        public virtual DbSet<TblCustomer> TblCustomer { get; set; }
        public virtual DbSet<TblCustomerBuysProductWithCash> TblCustomerBuysProductWithCash { get; set; }
        public virtual DbSet<TblCustomerBuysProductWithCreditCard> TblCustomerBuysProductWithCreditCard { get; set; }
        public virtual DbSet<TblDepartmentType> TblDepartmentType { get; set; }
        public virtual DbSet<TblEmployee> TblEmployee { get; set; }
        public virtual DbSet<TblEquipment> TblEquipment { get; set; }
        public virtual DbSet<TblFactory> TblFactory { get; set; }
        public virtual DbSet<TblFactoryHasEmployee> TblFactoryHasEmployee { get; set; }
        public virtual DbSet<TblFactoryHasEquipment> TblFactoryHasEquipment { get; set; }
        public virtual DbSet<TblFactoryHasVehicle> TblFactoryHasVehicle { get; set; }
        public virtual DbSet<TblFactoryInventory> TblFactoryInventory { get; set; }
        public virtual DbSet<TblFactoryProducedProduct> TblFactoryProducedProduct { get; set; }
        public virtual DbSet<TblFactoryProductProduction> TblFactoryProductProduction { get; set; }
        public virtual DbSet<TblFactorySendsProductToMarket> TblFactorySendsProductToMarket { get; set; }
        public virtual DbSet<TblFactorySendsProductToWarehouse> TblFactorySendsProductToWarehouse { get; set; }
        public virtual DbSet<TblMarket> TblMarket { get; set; }
        public virtual DbSet<TblMarketHasEmployee> TblMarketHasEmployee { get; set; }
        public virtual DbSet<TblMarketHasEquipment> TblMarketHasEquipment { get; set; }
        public virtual DbSet<TblMarketHasVehicle> TblMarketHasVehicle { get; set; }
        public virtual DbSet<TblMarketInventory> TblMarketInventory { get; set; }
        public virtual DbSet<TblPositionType> TblPositionType { get; set; }
        public virtual DbSet<TblProductBrand> TblProductBrand { get; set; }
        public virtual DbSet<TblProductKind> TblProductKind { get; set; }
        public virtual DbSet<TblProductTemplate> TblProductTemplate { get; set; }
        public virtual DbSet<TblProductType> TblProductType { get; set; }
        public virtual DbSet<TblProductUnit> TblProductUnit { get; set; }
        public virtual DbSet<TblProfession> TblProfession { get; set; }
        public virtual DbSet<TblRankType> TblRankType { get; set; }
        public virtual DbSet<TblVehicle> TblVehicle { get; set; }
        public virtual DbSet<TblVehicleBrand> TblVehicleBrand { get; set; }
        public virtual DbSet<TblVehicleModel> TblVehicleModel { get; set; }
        public virtual DbSet<TblVehicleType> TblVehicleType { get; set; }
        public virtual DbSet<TblWarehouse> TblWarehouse { get; set; }
        public virtual DbSet<TblWarehouseHasEmployee> TblWarehouseHasEmployee { get; set; }
        public virtual DbSet<TblWareHouseHasEquipment> TblWareHouseHasEquipment { get; set; }
        public virtual DbSet<TblWarehouseHasVehicle> TblWarehouseHasVehicle { get; set; }
        public virtual DbSet<TblWarehouseInventory> TblWarehouseInventory { get; set; }
        public virtual DbSet<TblWarehouseSendsToMarket> TblWarehouseSendsToMarket { get; set; }
    }
}
