//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAppCurrency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAppCurrency()
        {
            this.TblProductTemplate = new HashSet<TblProductTemplate>();
            this.TblCustomerBuysProductWithCash = new HashSet<TblCustomerBuysProductWithCash>();
            this.TblCustomerBuysProductWithCreditCard = new HashSet<TblCustomerBuysProductWithCreditCard>();
        }
    
        public int appCurrencyId { get; set; }
        public string appCurrencyCode { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductTemplate> TblProductTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCustomerBuysProductWithCash> TblCustomerBuysProductWithCash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCustomerBuysProductWithCreditCard> TblCustomerBuysProductWithCreditCard { get; set; }
    }
}
