//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCompany()
        {
            this.TblCompanyOwerHasCompany = new HashSet<TblCompanyOwerHasCompany>();
            this.TblCompanyHasFactory = new HashSet<TblCompanyHasFactory>();
            this.TblCompanyHasMarket = new HashSet<TblCompanyHasMarket>();
            this.TblCompanyHasWarehouse = new HashSet<TblCompanyHasWarehouse>();
        }
    
        public int companyId { get; set; }
        public string companyName { get; set; }
        public int companyType { get; set; }
        public int companyCountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyOwerHasCompany> TblCompanyOwerHasCompany { get; set; }
        public virtual TblCountry TblCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyHasFactory> TblCompanyHasFactory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyHasMarket> TblCompanyHasMarket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyHasWarehouse> TblCompanyHasWarehouse { get; set; }
        public virtual TblCompanyType TblCompanyType { get; set; }
    }
}
