//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompanyOwerHasCompany
    {
        public int CompanyOwerHasCompanyId { get; set; }
        public int companyOwner { get; set; }
        public int company { get; set; }
        public double companyOwnerPercent { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public bool isActive { get; set; }
    
        public virtual TblCompany TblCompany { get; set; }
        public virtual TblCompanyOwner TblCompanyOwner { get; set; }
    }
}
