//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompanyHasMarket
    {
        public int companyHasMarketId { get; set; }
        public int companyId { get; set; }
        public int marketId { get; set; }
        public Nullable<System.DateTime> ownershipStartDate { get; set; }
        public Nullable<System.DateTime> ownershipEndDate { get; set; }
    
        public virtual TblCompany TblCompany { get; set; }
        public virtual TblMarket TblMarket { get; set; }
    }
}
