//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompanyOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCompanyOwner()
        {
            this.TblCompanyOwerHasCompany = new HashSet<TblCompanyOwerHasCompany>();
        }
    
        public int companyOwnerId { get; set; }
        public string companyOwnerIdentityNumber { get; set; }
        public string companyOwnerName { get; set; }
        public string companyOwnerSurname { get; set; }
        public string companyOwnerEmail { get; set; }
        public string companyOwnerTelephoneNumber { get; set; }
        public string companyOwnerGender { get; set; }
        public System.DateTime companyOwnerBirthDate { get; set; }
        public string companyOwnerBirthPlace { get; set; }
        public string companyOwnerAddress { get; set; }
        public int companyOwnerProfession { get; set; }
        public string companyOwnerPassword { get; set; }
    
        public virtual TblProfession TblProfession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyOwerHasCompany> TblCompanyOwerHasCompany { get; set; }
    }
}
