//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomerBuysProductWithCreditCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCustomerBuysProductWithCreditCard()
        {
            this.TblCreditCardSaleDetail = new HashSet<TblCreditCardSaleDetail>();
        }
    
        public int customerBuysProductWithCreditCardId { get; set; }
        public int customerId { get; set; }
        public int marketId { get; set; }
        public decimal totalPrice { get; set; }
        public System.DateTime saleDate { get; set; }
        public int saleCurrency { get; set; }
        public string cardNameFirstAndLastTwocharacters { get; set; }
        public string cardNumberLastFourDigidts { get; set; }
        public short cardLastUseYear { get; set; }
    
        public virtual TblAppCurrency TblAppCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCreditCardSaleDetail> TblCreditCardSaleDetail { get; set; }
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblMarket TblMarket { get; set; }
    }
}
