//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactorySendsProductToMarket
    {
        public int factorySendsProductToMarketId { get; set; }
        public int factoryId { get; set; }
        public int marketId { get; set; }
        public int productTemplateId { get; set; }
        public long productQuantity { get; set; }
        public System.DateTime senddate { get; set; }
        public int sendVehicle { get; set; }
    
        public virtual TblFactory TblFactory { get; set; }
        public virtual TblMarket TblMarket { get; set; }
        public virtual TblProductTemplate TblProductTemplate { get; set; }
        public virtual TblVehicle TblVehicle { get; set; }
    }
}
