//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFactory()
        {
            this.TblCompanyHasFactory = new HashSet<TblCompanyHasFactory>();
            this.TblFactoryHasEquipment = new HashSet<TblFactoryHasEquipment>();
            this.TblFactoryHasEmployee = new HashSet<TblFactoryHasEmployee>();
            this.TblFactoryHasVehicle = new HashSet<TblFactoryHasVehicle>();
            this.TblFactoryInventory = new HashSet<TblFactoryInventory>();
            this.TblFactorySendsProductToMarket = new HashSet<TblFactorySendsProductToMarket>();
            this.TblFactorySendsProductToWarehouse = new HashSet<TblFactorySendsProductToWarehouse>();
            this.TblFactoryProducedProduct = new HashSet<TblFactoryProducedProduct>();
            this.TblFactoryProductProduction = new HashSet<TblFactoryProductProduction>();
        }
    
        public int factoryId { get; set; }
        public string factoryName { get; set; }
        public string factoryAddress { get; set; }
        public string factoryTelephoneNumber { get; set; }
        public string factoryEmail { get; set; }
        public int factoryCountry { get; set; }
        public string factoryProductionCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyHasFactory> TblCompanyHasFactory { get; set; }
        public virtual TblCountry TblCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryHasEquipment> TblFactoryHasEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryHasEmployee> TblFactoryHasEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryHasVehicle> TblFactoryHasVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryInventory> TblFactoryInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactorySendsProductToMarket> TblFactorySendsProductToMarket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactorySendsProductToWarehouse> TblFactorySendsProductToWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryProducedProduct> TblFactoryProducedProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryProductProduction> TblFactoryProductProduction { get; set; }
    }
}
