//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactoryProductProduction
    {
        public int factoryProductProductionId { get; set; }
        public int factoryId { get; set; }
        public int productTemplateId { get; set; }
        public int productQuantity { get; set; }
        public System.DateTime productionDate { get; set; }
        public int expirationDate { get; set; }
    
        public virtual TblFactory TblFactory { get; set; }
        public virtual TblProductTemplate TblProductTemplate { get; set; }
    }
}
