//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactoryHasEquipment
    {
        public int factoryHasequipmentId { get; set; }
        public int factoryId { get; set; }
        public int equipmentId { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public decimal purchasePrice { get; set; }
    
        public virtual TblEquipment TblEquipment { get; set; }
        public virtual TblFactory TblFactory { get; set; }
    }
}
