//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactoryProducedProduct
    {
        public int factoryProducedProductId { get; set; }
        public int factoryId { get; set; }
        public int productTemplateId { get; set; }
        public System.DateTime productiınDate { get; set; }
        public string barkod { get; set; }
    
        public virtual TblFactory TblFactory { get; set; }
        public virtual TblProductTemplate TblProductTemplate { get; set; }
    }
}
