//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactoryHasEmployee
    {
        public int factoryHasEmployeeId { get; set; }
        public int factoryId { get; set; }
        public int employeeId { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public bool isActive { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblFactory TblFactory { get; set; }
    }
}
