//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMarketInventory
    {
        public int marketInventoryId { get; set; }
        public int marketId { get; set; }
        public int productTemplateId { get; set; }
        public long totalAmount { get; set; }
    
        public virtual TblMarket TblMarket { get; set; }
        public virtual TblProductTemplate TblProductTemplate { get; set; }
    }
}
