//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMarketHasEmployee
    {
        public int marketHasEmployeeId { get; set; }
        public int marketId { get; set; }
        public int employeeId { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblMarket TblMarket { get; set; }
    }
}
