//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMarket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMarket()
        {
            this.TblCompanyHasMarket = new HashSet<TblCompanyHasMarket>();
            this.TblCustomerBuysProductWithCash = new HashSet<TblCustomerBuysProductWithCash>();
            this.TblCustomerBuysProductWithCreditCard = new HashSet<TblCustomerBuysProductWithCreditCard>();
            this.TblFactorySendsProductToMarket = new HashSet<TblFactorySendsProductToMarket>();
            this.TblMarketHasEmployee = new HashSet<TblMarketHasEmployee>();
            this.TblMarketHasEquipment = new HashSet<TblMarketHasEquipment>();
            this.TblMarketHasVehicle = new HashSet<TblMarketHasVehicle>();
            this.TblMarketInventory = new HashSet<TblMarketInventory>();
            this.TblWarehouseSendsToMarket = new HashSet<TblWarehouseSendsToMarket>();
        }
    
        public int marketId { get; set; }
        public string marketName { get; set; }
        public string marketAddress { get; set; }
        public string marketTelephoneNumber { get; set; }
        public string marketEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyHasMarket> TblCompanyHasMarket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCustomerBuysProductWithCash> TblCustomerBuysProductWithCash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCustomerBuysProductWithCreditCard> TblCustomerBuysProductWithCreditCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactorySendsProductToMarket> TblFactorySendsProductToMarket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMarketHasEmployee> TblMarketHasEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMarketHasEquipment> TblMarketHasEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMarketHasVehicle> TblMarketHasVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMarketInventory> TblMarketInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWarehouseSendsToMarket> TblWarehouseSendsToMarket { get; set; }
    }
}
