//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProductTemplate()
        {
            this.TblCashSaleDetail = new HashSet<TblCashSaleDetail>();
            this.TblCreditCardSaleDetail = new HashSet<TblCreditCardSaleDetail>();
            this.TblFactoryInventory = new HashSet<TblFactoryInventory>();
            this.TblFactoryProducedProduct = new HashSet<TblFactoryProducedProduct>();
            this.TblFactoryProductProduction = new HashSet<TblFactoryProductProduction>();
            this.TblFactorySendsProductToMarket = new HashSet<TblFactorySendsProductToMarket>();
            this.TblFactorySendsProductToWarehouse = new HashSet<TblFactorySendsProductToWarehouse>();
            this.TblMarketInventory = new HashSet<TblMarketInventory>();
            this.TblWarehouseInventory = new HashSet<TblWarehouseInventory>();
            this.TblWarehouseSendsToMarket = new HashSet<TblWarehouseSendsToMarket>();
        }
    
        public int productTemplateId { get; set; }
        public string productTemplateName { get; set; }
        public short productTemplateProfitPercent { get; set; }
        public byte productTemplateLifeTeamYear { get; set; }
        public int productTemplateCost { get; set; }
        public int productTemplateKind { get; set; }
        public int productTemplateType { get; set; }
        public int productTemplateBrand { get; set; }
        public int productTemplateUnit { get; set; }
        public int productTemplateCurrency { get; set; }
    
        public virtual TblAppCurrency TblAppCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCashSaleDetail> TblCashSaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCreditCardSaleDetail> TblCreditCardSaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryInventory> TblFactoryInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryProducedProduct> TblFactoryProducedProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactoryProductProduction> TblFactoryProductProduction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactorySendsProductToMarket> TblFactorySendsProductToMarket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactorySendsProductToWarehouse> TblFactorySendsProductToWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMarketInventory> TblMarketInventory { get; set; }
        public virtual TblProductBrand TblProductBrand { get; set; }
        public virtual TblProductKind TblProductKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWarehouseInventory> TblWarehouseInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWarehouseSendsToMarket> TblWarehouseSendsToMarket { get; set; }
        public virtual TblProductType TblProductType { get; set; }
        public virtual TblProductUnit TblProductUnit { get; set; }
    }
}
