//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAppProject.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblWarehouse()
        {
            this.TblCompanyHasWarehouse = new HashSet<TblCompanyHasWarehouse>();
            this.TblFactorySendsProductToWarehouse = new HashSet<TblFactorySendsProductToWarehouse>();
            this.TblWarehouseHasEmployee = new HashSet<TblWarehouseHasEmployee>();
            this.TblWareHouseHasEquipment = new HashSet<TblWareHouseHasEquipment>();
            this.TblWarehouseHasVehicle = new HashSet<TblWarehouseHasVehicle>();
            this.TblWarehouseInventory = new HashSet<TblWarehouseInventory>();
            this.TblWarehouseSendsToMarket = new HashSet<TblWarehouseSendsToMarket>();
        }
    
        public int warehouseId { get; set; }
        public string warehouseName { get; set; }
        public string warehouseAddress { get; set; }
        public string warehouseTelephoneNumber { get; set; }
        public string warehouseEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCompanyHasWarehouse> TblCompanyHasWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactorySendsProductToWarehouse> TblFactorySendsProductToWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWarehouseHasEmployee> TblWarehouseHasEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWareHouseHasEquipment> TblWareHouseHasEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWarehouseHasVehicle> TblWarehouseHasVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWarehouseInventory> TblWarehouseInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWarehouseSendsToMarket> TblWarehouseSendsToMarket { get; set; }
    }
}
