create table TblEmployee(
	employeeId int not null identity(1,1),
	employeeIdentityNumber varchar(15) not null,
	employeeName nvarchar(40) not null,
	employeeSurname nvarchar(40) not null,
	employeeEmail nvarchar(50) not null,
	employeeTelephoneNumber varchar(30) not null,
	employeeGender char(1) not null,
	employeeBirthDate date not null,
	employeeBirthPlace nvarchar(255) not null,
	employeeAddress nvarchar(255) not null,
	employeeRank int not null,
	employeePosition int not null,
	employeeDepartment int not null,
	employeeSalary decimal(18,2),
	constraint PK_employeeId primary key(employeeId),
	constraint CK_employeeIdentityNumber check(len(employeeIdentityNumber)>5),
	constraint CK_employeeName check(len(employeeName)>1),
	constraint CK_employeeSurname check(len(employeeSurname)>1),
	constraint CK_employeeGender check(employeeGender in ('M','F','N')),
	constraint FK_employeeRank foreign key(employeeRank) references TblRankType(rankTypeId),
	constraint FK_employeePosition foreign key(employeePosition) references TblPositionType(positionTypeId),
	constraint FK_employeeDepartment foreign key(employeeDepartment) references TblDepartmentType(departmentTypeId)
);